import { useGLTF, useVideoTexture } from "@react-three/drei";
import * as THREE from "three";
import { useGame } from "../store/useGame";
import { TV_STATE } from "../const";

// TODO
// 修复视频材质没有正好填满屏幕的问题
function Tv(props) {
  const videoTexture = useVideoTexture("./dogs.mp4");

  const { tvState } = useGame();

  const { nodes, materials } = useGLTF("./tv-v2.glb");
  return (
    <group {...props} dispose={null} userData={{ customName: "tv" }}>
      <group position={[0.57, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0001.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0002.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0003.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0004.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0005.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0006.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0007.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0008.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0009.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0011.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0012.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0013.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0014.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0015.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0016.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0017.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0018.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0019.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0020.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0021.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0022.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0023.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0024.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0025.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0026.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0027.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0028.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0029.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0030.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0031.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0032.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0033.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0034.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0035.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0036.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0037.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0038.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0039.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0040.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0041.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0042.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0043.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0044.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0045.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0046.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0047.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0048.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0049.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0050.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0051.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0052.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0053.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0054.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0055.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0056.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0057.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0058.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0059.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0060.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0061.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0062.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0063.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0064.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0065.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0066.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0067.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0068.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0069.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0070.geometry}
          material={materials.phong1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.led_tv_phong1_0071.geometry}
          material={materials.phong1}
        />

        {/* {tvState === TV_STATE.OPENED ? (
          <mesh castShadow receiveShadow geometry={nodes.screen.geometry}>
            <meshStandardMaterial
              side={THREE.DoubleSide}
              map={videoTexture}
              toneMapped={false}
            />
          </mesh>
        ) : (
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.screen.geometry}
            material={materials.phong1}
          />
        )} */}
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.screen.geometry}
          material={
            tvState === TV_STATE.OPENED
              ? new THREE.MeshBasicMaterial({
                  map: videoTexture,
                  toneMapped: false,
                })
              : materials.phong1
          }
        ></mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/tv-v2.glb");

export default Tv;
